"""
[
Country(alpha_2='CL', alpha_3='CHL', flag='🇨🇱', name='Chile', numeric='152', official_name='Republic of Chile')
Country(alpha_2='PL', alpha_3='POL', flag='🇵🇱', name='Poland', numeric='616', official_name='Republic of Poland')
Country(alpha_2='OM', alpha_3='OMN', flag='🇴🇲', name='Oman', numeric='512', official_name='Sultanate of Oman')
Country(alpha_2='BR', alpha_3='BRA', flag='🇧🇷', name='Brazil', numeric='076', official_name='Federative Republic of Brazil')
Country(alpha_2='SI', alpha_3='SVN', flag='🇸🇮', name='Slovenia', numeric='705', official_name='Republic of Slovenia')
Country(alpha_2='LU', alpha_3='LUX', flag='🇱🇺', name='Luxembourg', numeric='442', official_name='Grand Duchy of Luxembourg')
Country(alpha_2='LT', alpha_3='LTU', flag='🇱🇹', name='Lithuania', numeric='440', official_name='Republic of Lithuania')
Country(alpha_2='IE', alpha_3='IRL', flag='🇮🇪', name='Ireland', numeric='372')
Country(alpha_2='PA', alpha_3='PAN', flag='🇵🇦', name='Panama', numeric='591', official_name='Republic of Panama')
Country(alpha_2='HN', alpha_3='HND', flag='🇭🇳', name='Honduras', numeric='340', official_name='Republic of Honduras')
Country(alpha_2='BG', alpha_3='BGR', flag='🇧🇬', name='Bulgaria', numeric='100', official_name='Republic of Bulgaria')
Country(alpha_2='QA', alpha_3='QAT', flag='🇶🇦', name='Qatar', numeric='634', official_name='State of Qatar')
Country(alpha_2='MA', alpha_3='MAR', flag='🇲🇦', name='Morocco', numeric='504', official_name='Kingdom of Morocco')
Country(alpha_2='JM', alpha_3='JAM', flag='🇯🇲', name='Jamaica', numeric='388')
Country(alpha_2='CO', alpha_3='COL', flag='🇨🇴', name='Colombia', numeric='170', official_name='Republic of Colombia')
Country(alpha_2='MY', alpha_3='MYS', flag='🇲🇾', name='Malaysia', numeric='458')
Country(alpha_2='DJ', alpha_3='DJI', flag='🇩🇯', name='Djibouti', numeric='262', official_name='Republic of Djibouti')
Country(alpha_2='MD', alpha_3='MDA', common_name='Moldova', flag='🇲🇩', name='Moldova, Republic of', numeric='498', official_name='Republic of Moldova')
Country(alpha_2='IL', alpha_3='ISR', flag='🇮🇱', name='Israel', numeric='376', official_name='State of Israel')
Country(alpha_2='KW', alpha_3='KWT', flag='🇰🇼', name='Kuwait', numeric='414', official_name='State of Kuwait')
Country(alpha_2='DZ', alpha_3='DZA', flag='🇩🇿', name='Algeria', numeric='012', official_name="People's Democratic Republic of Algeria")
Country(alpha_2='PE', alpha_3='PER', flag='🇵🇪', name='Peru', numeric='604', official_name='Republic of Peru')
Country(alpha_2='TW', alpha_3='TWN', common_name='Taiwan', flag='🇹🇼', name='Taiwan, Province of China', numeric='158', official_name='Taiwan, Province of China')
Country(alpha_2='SA', alpha_3='SAU', flag='🇸🇦', name='Saudi Arabia', numeric='682', official_name='Kingdom of Saudi Arabia')
Country(alpha_2='BH', alpha_3='BHR', flag='🇧🇭', name='Bahrain', numeric='048', official_name='Kingdom of Bahrain')
Country(alpha_2='CY', alpha_3='CYP', flag='🇨🇾', name='Cyprus', numeric='196', official_name='Republic of Cyprus')
Country(alpha_2='GH', alpha_3='GHA', flag='🇬🇭', name='Ghana', numeric='288', official_name='Republic of Ghana')
Country(alpha_2='ES', alpha_3='ESP', flag='🇪🇸', name='Spain', numeric='724', official_name='Kingdom of Spain')
Country(alpha_2='CA', alpha_3='CAN', flag='🇨🇦', name='Canada', numeric='124')
Country(alpha_2='MT', alpha_3='MLT', flag='🇲🇹', name='Malta', numeric='470', official_name='Republic of Malta')
Country(alpha_2='PT', alpha_3='PRT', flag='🇵🇹', name='Portugal', numeric='620', official_name='Portuguese Republic')
Country(alpha_2='TM', alpha_3='TKM', flag='🇹🇲', name='Turkmenistan', numeric='795')
Country(alpha_2='SY', alpha_3='SYR', common_name='Syria', flag='🇸🇾', name='Syrian Arab Republic', numeric='760')
Country(alpha_2='KZ', alpha_3='KAZ', flag='🇰🇿', name='Kazakhstan', numeric='398', official_name='Republic of Kazakhstan')
Country(alpha_2='TR', alpha_3='TUR', flag='🇹🇷', name='Türkiye', numeric='792', official_name='Republic of Türkiye')
Country(alpha_2='RU', alpha_3='RUS', flag='🇷🇺', name='Russian Federation', numeric='643')
Country(alpha_2='IN', alpha_3='IND', flag='🇮🇳', name='India', numeric='356', official_name='Republic of India')
Country(alpha_2='MX', alpha_3='MEX', flag='🇲🇽', name='Mexico', numeric='484', official_name='United Mexican States')
Country(alpha_2='MV', alpha_3='MDV', flag='🇲🇻', name='Maldives', numeric='462', official_name='Republic of Maldives')
Country(alpha_2='TN', alpha_3='TUN', flag='🇹🇳', name='Tunisia', numeric='788', official_name='Republic of Tunisia')
Country(alpha_2='SD', alpha_3='SDN', flag='🇸🇩', name='Sudan', numeric='729', official_name='Republic of the Sudan')
Country(alpha_2='KR', alpha_3='KOR', common_name='South Korea', flag='🇰🇷', name='Korea, Republic of', numeric='410')
Country(alpha_2='HR', alpha_3='HRV', flag='🇭🇷', name='Croatia', numeric='191', official_name='Republic of Croatia')
Country(alpha_2='HK', alpha_3='HKG', flag='🇭🇰', name='Hong Kong', numeric='344', official_name='Hong Kong Special Administrative Region of China')
Country(alpha_2='GE', alpha_3='GEO', flag='🇬🇪', name='Georgia', numeric='268')
Country(alpha_2='NL', alpha_3='NLD', flag='🇳🇱', name='Netherlands', numeric='528', official_name='Kingdom of the Netherlands')
Country(alpha_2='NO', alpha_3='NOR', flag='🇳🇴', name='Norway', numeric='578', official_name='Kingdom of Norway')
Country(alpha_2='PH', alpha_3='PHL', flag='🇵🇭', name='Philippines', numeric='608', official_name='Republic of the Philippines')
Country(alpha_2='AE', alpha_3='ARE', flag='🇦🇪', name='United Arab Emirates', numeric='784')
Country(alpha_2='JO', alpha_3='JOR', flag='🇯🇴', name='Jordan', numeric='400', official_name='Hashemite Kingdom of Jordan')
Country(alpha_2='PS', alpha_3='PSE', flag='🇵🇸', name='Palestine, State of', numeric='275', official_name='the State of Palestine')
Country(alpha_2='CH', alpha_3='CHE', flag='🇨🇭', name='Switzerland', numeric='756', official_name='Swiss Confederation')
Country(alpha_2='ZA', alpha_3='ZAF', flag='🇿🇦', name='South Africa', numeric='710', official_name='Republic of South Africa')
Country(alpha_2='ET', alpha_3='ETH', flag='🇪🇹', name='Ethiopia', numeric='231', official_name='Federal Democratic Republic of Ethiopia')
Country(alpha_2='BW', alpha_3='BWA', flag='🇧🇼', name='Botswana', numeric='072', official_name='Republic of Botswana')
Country(alpha_2='FR', alpha_3='FRA', flag='🇫🇷', name='France', numeric='250', official_name='French Republic')
Country(alpha_2='AZ', alpha_3='AZE', flag='🇦🇿', name='Azerbaijan', numeric='031', official_name='Republic of Azerbaijan')
Country(alpha_2='FJ', alpha_3='FJI', flag='🇫🇯', name='Fiji', numeric='242', official_name='Republic of Fiji')
Country(alpha_2='GR', alpha_3='GRC', flag='🇬🇷', name='Greece', numeric='300', official_name='Hellenic Republic')
Country(alpha_2='NG', alpha_3='NGA', flag='🇳🇬', name='Nigeria', numeric='566', official_name='Federal Republic of Nigeria')
Country(alpha_2='RS', alpha_3='SRB', flag='🇷🇸', name='Serbia', numeric='688', official_name='Republic of Serbia')
Country(alpha_2='NA', alpha_3='NAM', flag='🇳🇦', name='Namibia', numeric='516', official_name='Republic of Namibia')
Country(alpha_2='EC', alpha_3='ECU', flag='🇪🇨', name='Ecuador', numeric='218', official_name='Republic of Ecuador')
Country(alpha_2='PR', alpha_3='PRI', flag='🇵🇷', name='Puerto Rico', numeric='630')
Country(alpha_2='YE', alpha_3='YEM', flag='🇾🇪', name='Yemen', numeric='887', official_name='Republic of Yemen')
Country(alpha_2='AL', alpha_3='ALB', flag='🇦🇱', name='Albania', numeric='008', official_name='Republic of Albania')
Country(alpha_2='BE', alpha_3='BEL', flag='🇧🇪', name='Belgium', numeric='056', official_name='Kingdom of Belgium')
Country(alpha_2='BD', alpha_3='BGD', flag='🇧🇩', name='Bangladesh', numeric='050', official_name="People's Republic of Bangladesh")
Country(alpha_2='FI', alpha_3='FIN', flag='🇫🇮', name='Finland', numeric='246', official_name='Republic of Finland')
Country(alpha_2='KH', alpha_3='KHM', flag='🇰🇭', name='Cambodia', numeric='116', official_name='Kingdom of Cambodia')
Country(alpha_2='CZ', alpha_3='CZE', flag='🇨🇿', name='Czechia', numeric='203', official_name='Czech Republic')
Country(alpha_2='IT', alpha_3='ITA', flag='🇮🇹', name='Italy', numeric='380', official_name='Italian Republic')
Country(alpha_2='AR', alpha_3='ARG', flag='🇦🇷', name='Argentina', numeric='032', official_name='Argentine Republic')
Country(alpha_2='AT', alpha_3='AUT', flag='🇦🇹', name='Austria', numeric='040', official_name='Republic of Austria')
Country(alpha_2='LY', alpha_3='LBY', flag='🇱🇾', name='Libya', numeric='434', official_name='Libya')
Country(alpha_2='BF', alpha_3='BFA', flag='🇧🇫', name='Burkina Faso', numeric='854')
Country(alpha_2='MO', alpha_3='MAC', flag='🇲🇴', name='Macao', numeric='446', official_name='Macao Special Administrative Region of China')
Country(alpha_2='GB', alpha_3='GBR', flag='🇬🇧', name='United Kingdom', numeric='826', official_name='United Kingdom of Great Britain and Northern Ireland')
Country(alpha_2='IS', alpha_3='ISL', flag='🇮🇸', name='Iceland', numeric='352', official_name='Republic of Iceland')
Country(alpha_2='HT', alpha_3='HTI', flag='🇭🇹', name='Haiti', numeric='332', official_name='Republic of Haiti')
Country(alpha_2='DK', alpha_3='DNK', flag='🇩🇰', name='Denmark', numeric='208', official_name='Kingdom of Denmark')
Country(alpha_2='CR', alpha_3='CRI', flag='🇨🇷', name='Costa Rica', numeric='188', official_name='Republic of Costa Rica')
Country(alpha_2='GT', alpha_3='GTM', flag='🇬🇹', name='Guatemala', numeric='320', official_name='Republic of Guatemala')
Country(alpha_2='MU', alpha_3='MUS', flag='🇲🇺', name='Mauritius', numeric='480', official_name='Republic of Mauritius')
Country(alpha_2='DE', alpha_3='DEU', flag='🇩🇪', name='Germany', numeric='276', official_name='Federal Republic of Germany')
Country(alpha_2='BO', alpha_3='BOL', common_name='Bolivia', flag='🇧🇴', name='Bolivia, Plurinational State of', numeric='068', official_name='Plurinational State of Bolivia')
Country(alpha_2='LB', alpha_3='LBN', flag='🇱🇧', name='Lebanon', numeric='422', official_name='Lebanese Republic')
Country(alpha_2='UY', alpha_3='URY', flag='🇺🇾', name='Uruguay', numeric='858', official_name='Eastern Republic of Uruguay')
Country(alpha_2='IQ', alpha_3='IRQ', flag='🇮🇶', name='Iraq', numeric='368', official_name='Republic of Iraq')
Country(alpha_2='SG', alpha_3='SGP', flag='🇸🇬', name='Singapore', numeric='702', official_name='Republic of Singapore')
Country(alpha_2='CM', alpha_3='CMR', flag='🇨🇲', name='Cameroon', numeric='120', official_name='Republic of Cameroon')
Country(alpha_2='HU', alpha_3='HUN', flag='🇭🇺', name='Hungary', numeric='348', official_name='Hungary')
Country(alpha_2='BN', alpha_3='BRN', flag='🇧🇳', name='Brunei Darussalam', numeric='096')
Country(alpha_2='ID', alpha_3='IDN', flag='🇮🇩', name='Indonesia', numeric='360', official_name='Republic of Indonesia')
Country(alpha_2='US', alpha_3='USA', flag='🇺🇸', name='United States', numeric='840', official_name='United States of America')
Country(alpha_2='AF', alpha_3='AFG', flag='🇦🇫', name='Afghanistan', numeric='004', official_name='Islamic Republic of Afghanistan')
Country(alpha_2='CN', alpha_3='CHN', flag='🇨🇳', name='China', numeric='156', official_name="People's Republic of China")
Country(alpha_2='AO', alpha_3='AGO', flag='🇦🇴', name='Angola', numeric='024', official_name='Republic of Angola')
Country(alpha_2='EE', alpha_3='EST', flag='🇪🇪', name='Estonia', numeric='233', official_name='Republic of Estonia')
Country(alpha_2='JP', alpha_3='JPN', flag='🇯🇵', name='Japan', numeric='392')
Country(alpha_2='EG', alpha_3='EGY', flag='🇪🇬', name='Egypt', numeric='818', official_name='Arab Republic of Egypt')
Country(alpha_2='IR', alpha_3='IRN', common_name='Iran', flag='🇮🇷', name='Iran, Islamic Republic of', numeric='364', official_name='Islamic Republic of Iran')
Country(alpha_2='SV', alpha_3='SLV', flag='🇸🇻', name='El Salvador', numeric='222', official_name='Republic of El Salvador')
Country(alpha_2='BI', alpha_3='BDI', flag='🇧🇮', name='Burundi', numeric='108', official_name='Republic of Burundi')
Country(alpha_2='SE', alpha_3='SWE', flag='🇸🇪', name='Sweden', numeric='752', official_name='Kingdom of Sweden')
"""